from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .evidence import evidence_as_prompt, select_evidence
from .llm_client import call_openai_json, render_prompt


def run_model_spec(
    *,
    target: dict[str, Any],
    text_json: dict[str, Any],
    schema_path: str | Path,
    prompt_path: str | Path,
    offline: bool = False,
) -> dict[str, Any]:
    if offline:
        return offline_model_spec(target)
    schema = json.loads(Path(schema_path).read_text(encoding="utf-8"))
    metadata = json.dumps(target, ensure_ascii=False, indent=2)
    prompt = render_prompt(
        prompt_path,
        metadata=metadata,
        evidence=evidence_as_prompt(select_evidence(text_json), max_chars=16000),
    )
    return call_openai_json(prompt=prompt, schema=schema, schema_name="model_spec")


def offline_model_spec(target: dict[str, Any]) -> dict[str, Any]:
    return {
        "sets": [
            "Buses b in B",
            "Generators i in G",
            "Transmission lines l in L",
            "Wind farms w in W",
            "Time periods t in T",
            "Worst-case scenarios s in S generated by C&CG",
        ],
        "parameters": [
            "Generator fixed, startup, shutdown, marginal, reserve, ramp, min/max output costs and limits",
            "Forecast load and wind profiles",
            "Load-shift-factor matrix and line limits",
            "Box uncertainty bounds for load and wind",
        ],
        "variables": [
            "Commitment, startup, shutdown binary variables",
            "Dispatch and piecewise marginal generation variables",
            "Spinning and operating reserve variables",
            "Second-stage recourse dispatch variables for each generated scenario",
        ],
        "objective": "Minimize first-stage unit commitment cost plus worst-case second-stage dispatch cost.",
        "constraints": [
            "Minimum up/down time",
            "Ramping",
            "Generation capacity and piecewise production",
            "System power balance",
            "Reserve requirements",
            "Transmission line limits via load-shift factors",
            "Robust feasibility over generated worst-case scenarios",
        ],
        "uncertainty": [
            "Uncertain wind power and load modeled by a bounded polyhedral/box uncertainty set",
            "Paper reports +/-20% wind uncertainty and +/-3% load uncertainty",
        ],
        "implementation_notes": [
            "Start with deterministic UC appendix.",
            "Add C&CG master and feasibility subproblem before runtime accelerations.",
            "Use LSF cutting-plane for the master problem as the first acceleration.",
        ],
    }


def model_spec_to_markdown(spec: dict[str, Any]) -> str:
    lines = ["# Model Spec", ""]
    for key in ["sets", "parameters", "variables", "constraints", "uncertainty", "implementation_notes"]:
        title = key.replace("_", " ").title()
        lines += [f"## {title}", ""]
        lines += [f"- {item}" for item in spec.get(key, [])]
        lines.append("")
    lines += ["## Objective", "", spec.get("objective", ""), ""]
    return "\n".join(lines)

